# Form implementation generated from reading ui file 'ui_pageAdd.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(539, 227)
        Dialog.setStyleSheet("color: black;\n"
"background-color: rgb(220, 228, 235)")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(0, 0, 0, 30);\n"
"border-radius: 7px;")
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("color: black;\n"
"font-weight: bold;\n"
"font-size: 15pt;\n"
"background-color: none;\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setStyleSheet("background-color: none;\n"
"border: none;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_stationName = QtWidgets.QLineEdit(parent=self.frame)
        self.le_stationName.setObjectName("le_stationName")
        self.verticalLayout.addWidget(self.le_stationName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_lat_deg = QtWidgets.QLineEdit(parent=self.frame)
        self.le_lat_deg.setObjectName("le_lat_deg")
        self.horizontalLayout.addWidget(self.le_lat_deg)
        self.le_lat_min = QtWidgets.QLineEdit(parent=self.frame)
        self.le_lat_min.setObjectName("le_lat_min")
        self.horizontalLayout.addWidget(self.le_lat_min)
        self.le_lat_sec = QtWidgets.QLineEdit(parent=self.frame)
        self.le_lat_sec.setObjectName("le_lat_sec")
        self.horizontalLayout.addWidget(self.le_lat_sec)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_long_deg = QtWidgets.QLineEdit(parent=self.frame)
        self.le_long_deg.setObjectName("le_long_deg")
        self.horizontalLayout_2.addWidget(self.le_long_deg)
        self.le_long_min = QtWidgets.QLineEdit(parent=self.frame)
        self.le_long_min.setObjectName("le_long_min")
        self.horizontalLayout_2.addWidget(self.le_long_min)
        self.le_long_sec = QtWidgets.QLineEdit(parent=self.frame)
        self.le_long_sec.setObjectName("le_long_sec")
        self.horizontalLayout_2.addWidget(self.le_long_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.le_stationSpeed = QtWidgets.QLineEdit(parent=self.frame)
        self.le_stationSpeed.setObjectName("le_stationSpeed")
        self.verticalLayout.addWidget(self.le_stationSpeed)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pb_save_station = QtWidgets.QPushButton(parent=self.frame)
        self.pb_save_station.setObjectName("pb_save_station")
        self.verticalLayout_3.addWidget(self.pb_save_station)
        self.verticalLayout_4.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Новая станция"))
        self.label_2.setText(_translate("Dialog", "Название"))
        self.label_3.setText(_translate("Dialog", "Широта"))
        self.label_4.setText(_translate("Dialog", "Долгота"))
        self.label_5.setText(_translate("Dialog", "Скорость (км/ч) "))
        self.le_lat_deg.setPlaceholderText(_translate("Dialog", "Градусы"))
        self.le_lat_min.setPlaceholderText(_translate("Dialog", "Минуты"))
        self.le_lat_sec.setPlaceholderText(_translate("Dialog", "Секунды"))
        self.le_long_deg.setPlaceholderText(_translate("Dialog", "Градусы"))
        self.le_long_min.setPlaceholderText(_translate("Dialog", "Минуты"))
        self.le_long_sec.setPlaceholderText(_translate("Dialog", "Секунды"))
        self.le_stationSpeed.setPlaceholderText(_translate("Dialog", "(прим. 40)"))
        self.pb_save_station.setText(_translate("Dialog", "Сохранить станцию"))
